### ISSUE TITLE
pep257 use config file

### ISSUE THREAD

**Issue by jakirkham** [PyCQA/prospector#124]
Much like pep8, pep257 allows for configuration to be supplied through config file (e.g. `setup.cfg`, `tox.ini`, or `.pep257`). However, this functionality does not appear to be supported in `prospector` at present. It would be nice to see this added. If this is possible and I am missing something, please help me understand how to go about doing this.

**Comment by tomato42** [comment]
+1 lack of support for this (and apparent override by `prospector` of the default config in `pep257`) cause it to regress the https://github.com/GreenSteam/pep257/issues/141 issue

**Comment by tomato42** [comment]
that being said, it is possible to change `pep257` configuration when run under `prospector`. In `.landscape.yaml` add following section to disable e.g. error D211:
```
pep257:
    disable:
        - D211
```

see documentation here: https://docs.landscape.io/advanced.html#existing-configuration

**Comment by jakirkham** [comment]
Friendly nudge. Any news on this?

**Comment by jakirkham** [comment]
Was there a fix somewhere for this issue?

**Comment by FraBle** [comment]
Has this ever been fixed?
What is the current approach to fix the conflict between D203 and D211 as mentioned above (https://github.com/PyCQA/pydocstyle/issues/141) by @tomato42
