### ISSUE TITLE
Subclasses of Manager show Errors about "Use of super on an old style class"

### ISSUE THREAD

**Issue by cancan101** [PyCQA/prospector#126]
```
class ThingManager(Manager):
46:     _queryset_class = ThingQuerySet
47: 
48:     def create(self, *args, **kwargs):
Use of super on an old style class
49:         id = kwargs.pop('id', None) or uuid.uuid4()
```

**Comment by jmagnusson** [comment]
I also get this a lot. My code is made for Python 3 only.

Example code that would generate the error you mentioned:

"""python
class MyClass(OtherClass):
    def render(self, text, **overrides):
        if not text:
            return ''
        return super().render(text, **overrides)
"""
