### ISSUE TITLE
Prospector Pylint Disable Error Code Not Working

### ISSUE THREAD

**Issue by muthuegrove** [PyCQA/prospector#157]
In pylintrc disabled the model-missing-unicode error, But its not working as we expected in prospector. But its working fine in pylint command execution.

**In .pylintrc,**

disable=model-missing-unicode
(or)
disable=W5101 # W5101 - No **unicode** method on model

Same output for both disable error code

**## OutPut**
  Line: 177
    pylint: model-missing-unicode / No **unicode** method on model (Model1)
  Line: 184
    pylint: model-no-explicit-unicode / Model does not explicitly define **unicode** (Model2)
  Line: 190
    pylint: model-missing-unicode / No **unicode** method on model (Model3)
  Line: 199
    pylint: model-missing-unicode / No **unicode** method on model (Model4)

**Note:**
**pylint result:**
I:104, 0: Locally disabling model-missing-unicode (W5101) (locally-disabled)

**Comment by carlio** [comment]
Is this still an issue? I'm trying to clear out old issues that may have accidentally been fixed in the last 2 years
