### ISSUE TITLE
PyLint warning `deprecated-method` not reported

### ISSUE THREAD

**Issue by bittner** [PyCQA/prospector#188]
I noticed that PyLint reports a warning that I had thought is a critical piece of information. Prospector doesn't report it, neither with `--strictness high` nor `--strictness veryhigh`:

``` python
W: 48, 8: Using deprecated method warn() (deprecated-method)
W: 52, 8: Using deprecated method warn() (deprecated-method)
```

This is for Python code using the `warn()` method of [logging](https://docs.python.org/3/library/logging.html#logging.Logger.warning), instead of `warning()`, e.g.

``` python
import logging

logger = logging.getLogger(__file__)

logger.warn('This call should better use the `warning` method.')
```

Is there a reason why prospector is not reporting this warning? I think it should.

**Comment by carlio** [comment]
Seems there was a commit to fix this ; as I am on a rampage of 2-year-old-bug closing, I hope it is fixed by now but please reopen if not.
