### ISSUE TITLE
Prospector error traceback doesn't get forwarded to Lanscape web UI, which may be preventing prospector bugs from getting diagnosed properly

### ISSUE THREAD

**Issue by mbdevpl** [PyCQA/prospector#197]
Since almost 2 months ago, I've been having a mysterious issue with one of my projects, i.e.

`argunparse`:
 - repo: https://github.com/mbdevpl/argunparse
 - landscape: https://landscape.io/github/mbdevpl/argunparse

The issue shows up as:

>  Check number 4 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
Failure reason: Prospector execution failed

However, have developers been notified? There seem to be few of those kinds of issues, some of them I link here:

- https://github.com/landscapeio/landscape-issues/issues/239
- https://github.com/landscapeio/landscape-issues/issues/233
- https://github.com/landscapeio/landscape-issues/issues/212
- https://github.com/landscapeio/landscape-issues/issues/95

Some of these are aggregates for probably several unrelated issues.

I installed latest `prospector` package via `pip`. I'm using Python 3.5.2. In my case, when I run the prospector offline (from the root directory of my project, and without any arguments), I get the following traceback:

```
Traceback (most recent call last):
  File "/.../bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/.../lib/python3.5/site-packages/prospector/run.py", line 154, in main
    config = ProspectorConfig()
  File "/.../lib/python3.5/site-packages/prospector/config/__init__.py", line 33, in __init__
    self.profile, self.strictness = self._get_profile(self.workdir, self.config)
  File "/.../lib/python3.5/site-packages/prospector/config/__init__.py", line 152, in _get_profile
    profile = ProspectorProfile.load(profile_name, profile_path, forced_inherits=forced_inherits)
  File "/.../lib/python3.5/site-packages/prospector/profiles/profile.py", line 119, in load
    forced_inherits=forced_inherits or [])
  File "/.../lib/python3.5/site-packages/prospector/profiles/profile.py", line 318, in _load_and_merge
    merged = _merge_profile_dict(priority, merged)
  File "/.../lib/python3.5/site-packages/prospector/profiles/profile.py", line 207, in _merge_profile_dict
    out[key] = _merge_tool_config(value, base.get(key, {}))
  File "/.../lib/python3.5/site-packages/prospector/profiles/profile.py", line 177, in _merge_tool_config
    out[key] = _simple_merge_dict(value, base.get(key, {}))
  File "/.../lib/python3.5/site-packages/prospector/profiles/profile.py", line 167, in _simple_merge_dict
    out.update(dict(priority.items()))
AttributeError: 'list' object has no attribute 'items'
```

However I'm not sure if it's the same error as online. In the issues listed above one of the issues is apparently not reproducible offline. Could there be some way of seeing the traceback of the error from the web UI? Can there be some tracking for those errors?

BTW, about the error, `priority` seems to be expected to be of type `dict`. But then, why is it iterated over and new dict `dict(priority.items())` constructed from it, before updating other dict `out` with values from it?

**Comment by mbdevpl** [comment]
BTW I got my issue fixed by removing two characters from the config file, please see: https://github.com/mbdevpl/argunparse/commit/86d51716e0376747fbad571799634e7a46e2cdf4

The config was valid YAML before that commit, and the prospector's parser parsed it, but then somehow prospector wasn't prepared for the correctly parsed config...

**Comment by carlio** [comment]
Prospector and Landscape have slightly diverged for now so the context for this is no longer relevant ; changes are being made to both so I will close this as "didn't fix for 2 years" and "probably no longer relevant"
