### ISSUE TITLE
Support mypy

### ISSUE THREAD

**Issue by tuukkamustonen** [PyCQA/prospector#198]
[mypy](https://github.com/python/mypy) static checks source code for type (annotation) violations. The ouput is pretty similar to other tools, e.g.:

```
fs/csm/common/model.py: note: In member "__init__" of class "StrProxy":
fs/csm/common/model.py:24: error: The return type of "__init__" must be None
fs/csm/common/logic/bundle.py: note: In member "__init__" of class "Bundle":
fs/csm/common/logic/bundle.py:8: error: The return type of "__init__" must be None
fs/csm/__init__.py: note: At top level:
fs/csm/__init__.py:2: error: Cannot determine type of '__path__'
fs/__init__.py:2: error: Cannot determine type of '__path__'
```

Would be nice to control `mypy` through `prospector` as well (to get pylint-compatible output etc.).

**Comment by carlio** [comment]
That PR just got added to latest release 1.0 so will close this unless there are any issues.
