### ISSUE TITLE
same output as landscape.io

### ISSUE THREAD

**Issue by grizz** [PyCQA/prospector#204]
Not really a bug, but I can't find a way to make prospector give the same output landscape.io does, what am I missing?

**Comment by carlio** [comment]
@grizz could be one of several things, what difference exactly? most likely slight differences in dependency versions between what you're running locally and what's running on Landscape.

**Comment by grizz** [comment]
@carlio prospector shows 4 messages, https://landscape.io/github/20c/pybird/13 shows 38 messages

I just did a fresh `pip install -U  'prospector[with_everything]`

```
$ git rev-parse --short HEAD
1f8ec24

$ prospector -P .landscape.yml  | grep 'Messages Found'
  Messages Found: 4

$ prospector --version
prospector 0.12.4
```

Is there any other information you'd like?

Cheers

**Comment by Pawamoy** [comment]
I think it's because pylint integration is broken. There is a pull request for it: https://github.com/landscapeio/prospector/pull/193.

**Comment by carlio** [comment]
Closing this as prospector and landscape are no longer completely aligned (and landscape will be getting a big change soon too so...)
