### ISSUE TITLE
Documentation: commandline options with doubled dashes not correctly generated

### ISSUE THREAD

**Issue by IceflowRE** [PyCQA/prospector#213]
https://github.com/landscapeio/prospector/blob/master/docs/usage.rst
http://prospector.landscape.io/en/master/usage.html
The part
```
.. argparse::
   :module: prospector.run
   :func: get_parser
   :prog: prospector
```
does not generate the `Named Arguments` part correctly.
Doubled dashes will merged into one.

**Comment by carlio** [comment]
I don't quite understand what the issue is but at least currently the named arguments part seems fine.
