### ISSUE TITLE
Support pydocstyle and pycodestyle names in config

### ISSUE THREAD

**Issue by pawamoy** [PyCQA/prospector#222]
Since pep8 and pep257 have changed their names to pycodestyle and pydocstyle, we should be able to configurate these tools with their new names (and see the new names in the output of prospector, like `Tools Run: pydocstyle, pycodestyle, profile-validator` instead of `Tools Run: pep257, pep8, profile-validator`).

**Comment by carlio** [comment]
Finally done in 1.7.0 release
