### ISSUE TITLE
Unused imports from usage of typing module in type hints.

### ISSUE THREAD

**Issue by timsavage** [PyCQA/prospector#225]
I am getting a large number of unused import errors due to the using of the typing module and backwards compatible type hints. eg:

```python
from typing import List


def to_list(str):
    # type: (str) -> List[str]
    ...
```
As the type hint and usage of `List` is not technically code it is being reported, however, this is using syntax suggested by [PEP-484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) for compatibility with Python 2.7.

**Comment by chocoelho** [comment]
This will be handled on `pylint` once `astroid` with `typed_ast` is supported. It was recently solved on `astroid`. See: https://github.com/PyCQA/astroid/issues/317
