### ISSUE TITLE
option –pylint-config-file does not work 

### ISSUE THREAD

**Issue by 1oglop1** [PyCQA/prospector#226]
Steps to reproduce:
1) run `prospector -DFM -s veryhigh –pylint-config-file pylintrc` 
or
1) run `prospector -DFM -s veryhigh –pylint-config-file "/full/path/pylintrc` 

Current behaviour:
 `In multi-path mode, all inputs must be files, not directories.`

Expected behaviuor: 
Use the `pylintrc` file.

**Comment by chocoelho** [comment]
Is this still happening? I've tried to reproduce it, but it seems to be working properly.

**Comment by 1oglop1** [comment]
Well the issue is pretty old, I haven't used prospector since, in favor of native tools.

**Comment by chocoelho** [comment]
Closing this since we're unable to reproduce it for now.
