### ISSUE TITLE
Add Python 3.5/3.6 support

### ISSUE THREAD

**Issue by tnir** [PyCQA/prospector#233]

**Comment by vsoch** [comment]
hey @carlio @tnir I'm coming late to this issue, but how hard would this be to implement? We'd really like prospector up and working for newer version of python 3, and as of now we are getting massive prints of this try catch statement:

```python
  return tokenize.open(filepath).read()
/home/vanessa/Documents/Dropbox/Code/Python/easybuild/vsc-install/.eggs/prospector-0.12.7-py3.5.egg/prospector/encoding.py:32: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/vanessa/Documents/Dropbox/Code/Python/easybuild/vsc-install/.eggs/pylint-1.8.4-py3.5.egg/pylint/__pkginfo__.py' mode='r' encoding='utf-8'>
```
I will appropriately add my hearts and thumbs up to this issue, thank you!
