### ISSUE TITLE
prospector installs django when django is not detected as requirement

### ISSUE THREAD

**Issue by JensTimmerman** [PyCQA/prospector#245]
Since pylint-django added django as a requirement, and pylint-django is a requirement of prospector, django is pulled in for all tests that use prospector. (https://github.com/PyCQA/pylint-django/pull/132)

Even though requirements detector does not detect anything django related, pytlink-django is installed, which in turn installs django (which fails on python 2.7 if you don't specify django 1.11)

**Comment by chocoelho** [comment]
IMHO, prospector shouldn't install pylint plugins such as `pylint-celery`, `pylint-django` and `pylint-flask`, since this should be handled through each project pylint configuration (meaning inside `pylintrc`).

**Comment by JensTimmerman** [comment]
seems to be fixed by https://github.com/PyCQA/pylint-django/pull/132
