### ISSUE TITLE
add command line option to write to file

### ISSUE THREAD

**Issue by dmashine** [PyCQA/prospector#246]
```
def print_messages(self, write_to=None):
   write_to = write_to or sys.stdout
```

write_to is already defined. Please add a command line option (like prospector --write-to=file.xml) so output will be in this file.

it is needed, because tox dont support pipeline redirects and someone may want to output file in xunit format.

**Comment by tysonclugg** [comment]
I'd like for prospector to be able to write xunit output to a file, in addition to showing grouped output on `stdout`.  Perhaps with invocation like this:
```
prospector -o xunit:reports/prospector.xml -o grouped
```

**Comment by chocoelho** [comment]
@tysonclugg you mean just like `pytest-cov` does? That'd be great.

**Comment by carlio** [comment]
That PR is merged now so should be working!
