### ISSUE TITLE
Relaxing pyroma constraint

### ISSUE THREAD

**Issue by jakirkham** [PyCQA/prospector#253]
It appears the `pyroma` constraint is extremely tight ( [exactly 2.0.2]( https://github.com/PyCQA/prospector/blob/0.12.8/setup.py#L60 ) ). The commit message seems to suggest this was needed a while back, but is not necessarily still needed now. Could it be relaxed?

**Comment by chocoelho** [comment]
It required some changes, but it's working now. Releasing a new patch soon.

**Comment by jakirkham** [comment]
Thank you :)

**Comment by jakirkham** [comment]
Had a [follow-up question]( https://github.com/PyCQA/prospector/commit/d0c416a715a2edc862d1cc8e0d19e3b909428dc8#r29137604 ) when you have a chance to look.
