### ISSUE TITLE
Pylint check broken with Pylint >= 2.0.0

### ISSUE THREAD

**Issue by volans-** [PyCQA/prospector#263]
In [pylint/collector.py#26](https://github.com/PyCQA/prospector/blob/master/prospector/tools/pylint/collector.py#L26) this expression is used:
```python
msg_data = self._message_store.check_message_id(msg_id)
```

But since https://github.com/PyCQA/pylint/pull/2077 was merged and then released, that method has been refactored to a different name: `get_message_definition()`. Hence now Prospector fails the pylint check with (only last part of the stacktrace attached):
```python
  File "venv/lib/python3.6/site-packages/prospector/tools/pylint/collector.py", line 26, in add_message
    msg_data = self._message_store.check_message_id(msg_id)
AttributeError: 'MessagesStore' object has no attribute 'check_message_id'
```

Related package versions:
```
prospector==1.0
pylint==2.0.1
```

**Comment by matthewdeanmartin** [comment]
I also started getting a bunch of errors (on travis but not mac), despite adding `output-format: grouped`. Then I started to get errors inside pylint. So I rolled pylint back to 1.9.2 & things build again.

```
  File "/home/travis/virtualenv/python3.6.3/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/run.py", line 174, in main
    prospector.print_messages()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/prospector/run.py", line 132, in print_messages
    formatter = FORMATTERS[output_format](self.summary, self.messages, self.config.profile)
KeyError: None
```

**Comment by chocoelho** [comment]
It's resolved in `develop` branch, but we'll need to wait until https://github.com/landscapeio/pylint-common/pull/10 is merged.

**Comment by chocoelho** [comment]
@matthewdeanmartin the fix for is related to: https://github.com/PyCQA/prospector/pull/262

**Comment by volans-** [comment]
@chocoelho thanks for the fix, tested and works as expected.
