### ISSUE TITLE
[QUESTION] Drop Python2 support from release 1.0 onward

### ISSUE THREAD

**Issue by carlio** [PyCQA/prospector#265]
This is just a place for discussion. @chocoelho mentioning you to make sure you see this, but any discussion is welcome.

Various libraries and tools used by prospector, especially pylint and sub-dependencies, have dropped Python 2 support.

Therefore I think that Prospector should do the same now that release '1.0' is out. The 0.x series of releases will keep it, so anyone still using Python 2 can stick to 0.12.x and if very necessary, we can continue releasing a separate 'fork' but I'd suggest trying to avoid working on it too much as it will require backporting and lots of compatability code.

**Comment by cadu-leite** [comment]
well...  is it seems to be my case ?   ...  trying refact old project ... try to run "prospector"

**Comment by chocoelho** [comment]
I'm in favor of this. Although the codebase using Python 2 may still be considerable, there's a trend to drop Python 2 support and we should follow it. There are lots of niceties in the more recent versions of Python and we can consider taking advantage of it.

**Comment by carlio** [comment]
@chocoelho I have created a fork at @landscapeio/prospector2 where I will keep some python2 compatibility - mostly to help keep landscape.io running - so we can officially drop it in this main prospector fork if you agree.
