### ISSUE TITLE
Pyroma 2.4 breaks prospector

### ISSUE THREAD

**Issue by tylerstapler-wf** [PyCQA/prospector#276]
I get this error when running prospector with pyroma 2.4 installed.

```shell
prospector
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 7, in <module>
    from prospector.run import main
  File "/usr/local/lib/python3.6/site-packages/prospector/run.py", line 8, in
 <module>
    from prospector import blender, postfilter, tools
  File "/usr/local/lib/python3.6/site-packages/prospector/tools/__init__.py",
 line 48, in <module>
    'pyroma': _optional_tool('pyroma'),
  File "/usr/local/lib/python3.6/site-packages/prospector/tools/__init__.py",
 line 29, in _optional_tool
    tool_package = __import__(package_name, fromlist=[tool_class_name])
  File "/usr/local/lib/python3.6/site-packages/prospector/tools/pyroma/__init
__.py", line 40, in <module>
    ratings.PackageDocs: 'PYR17',
AttributeError: module 'pyroma.ratings' has no attribute 'PackageDocs'
```

**Comment by volans-** [comment]
Confirmed

**Comment by carlio** [comment]
@volans- thanks for the PR. I fixed this locally before noticing your PR however yours is a better approach so I merged it over the top of my fix :-)

**Comment by tylerstapler-wf** [comment]
Thanks for the quick fix!

**Comment by volans-** [comment]
@carlio thanks for accepting my PR and make already new release!

I've tried to keep the diff at the minimum in that PR, but I think it's possible to clean it up a bit more in case you want, getting rid of both `PYROMA_CODES` and `PYROMA_TEST_CLASSES` variables altogether and using `__name__` to get the name of the classes and check them in the mapping.
