### ISSUE TITLE
Link to Built-in Profiles broken

### ISSUE THREAD

**Issue by Copper-Head** [PyCQA/prospector#288]
In [this documentation section](https://prospector.readthedocs.io/en/master/profiles.html#builtin-profiles) the [link to built-in profiles](https://github.com/landscapeio/prospector/tree/master/prospector/profiles/profiles) is broken.

**Comment by chocoelho** [comment]
Fixed :) And actually, the link is supposed to be to the paths `prospector` will look for a configuration file, not the built-in profiles.

**Comment by chocoelho** [comment]
But since it seems relevant to have this linked, I've added a link to the [built-in profiles](https://github.com/PyCQA/prospector/tree/master/prospector/profiles/profiles) to the proper [Profile Path](https://prospector.landscape.io/en/master/profiles.html#profile-path) documentation section.
