### ISSUE TITLE
Test files are not excluded by default

### ISSUE THREAD

**Issue by saifrim** [PyCQA/prospector#290]
**Enviroment:**
```
Python 2.7.10
prospector==1.1.4
pylint==1.9.3
```
**.prospector.yaml**
```
pep8:
  run: false

dodgy:
  run: false

mccabe:
  run: false

pyflakes:
  run: false
```

**~/pros: prospector --profile=.prospector.yaml company/tests/test_company.py**
```
Messages
========

company/tests/test_company.py
  Line: 1
    pylint: unused-import / Unused b64decode imported from base64



Check Information
=================
         Started: 2018-11-12 17:04:06.237579
        Finished: 2018-11-12 17:04:06.346525
      Time Taken: 0.11 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, no_doc_warnings, no_member_warnings, no_test_warnings, strictness_medium, strictness_high, strictness_veryhigh
      Strictness: from profile
  Libraries Used:
       Tools Run: profile-validator, pylint
  Messages Found: 1
```
The output for **--show-profile**:
```
...
ignore-patterns: ['^docs?/', '^tests?/?', '/tests?(/|$)', '(^|/)test_[_a-zA-Z0-9]+.py$',
  '(^|/)[_a-zA-Z0-9]+_tests?.py$', '(^|/)tests?.py', ^setup.py$, (^|/)\..+]
...
```

**Comment by carlio** [comment]
Specifying a specific file changes how files to test are found. 'ignore-patterns' is designed when pointing at a directory, but if you specify a single fine it assumes that you only want to test that file so skips filters. By giving it a single file, you're overriding the discovery mechanism which is where the filtering takes place.

**Comment by carlio** [comment]
(also side note - if you only want to run pylint you could either run pylint directly or `prospector -t pylint` and you wouldn't need the profile. that has nothing to do with this issue just a hint that might simplify things for you)
