### ISSUE TITLE
Flake8 latest version now uses pyflakes 2.0.0, and breaks prospector,

### ISSUE THREAD

**Issue by IDerr** [PyCQA/prospector#307]
When installing prospector with flake8 latest version, you have a warning :
```
prospector 1.1.6.2 has requirement pyflakes<2.0.0,>=0.8.1, but you'll have pyflakes 2.0.0 which is incompatible.

```
Flake8 now uses pyflakes 2.0.0
https://gitlab.com/pycqa/flake8/blob/master/setup.py#L25
and is restricted by prospector 
https://github.com/PyCQA/prospector/blob/8bb1970aa31b962291ef0cff4b757a34aa566298/setup.py#L29

Is it possible to be compatible with this new version?

Thanks a lot for your work

**Comment by carlio** [comment]
Pull requests always welcome!

**Comment by IDerr** [comment]
@carlio  I have opened a PR :D

**Comment by chocoelho** [comment]
Closing this issue as it is fixed in the new version of prospector to be released soon
