### ISSUE TITLE
check single files

### ISSUE THREAD

**Issue by techdragon** [PyCQA/prospector#31]
Can prospector be given an option to check single files? 

Having a single file mode would make building a prospector powered atom.io linter possible.

**Comment by jeffwidman** [comment]
@cjb any interest in putting together a atom.io linter for this?

**Comment by cjb** [comment]
I'm afraid I don't write Python anymore, but I think it would involve forking https://atom.io/packages/linter-pylint and changing the executable name and output regex.

**Comment by cjb** [comment]
I just realized how quickly you added this  feature, thanks very much for that! Sorry we didn't follow up :)
