### ISSUE TITLE
pep8 and pylint both report issue with singleton-comparison

### ISSUE THREAD

**Issue by andrehsu** [PyCQA/prospector#312]
Both pep8 and pylint show that there are problems with singleton-comparison

for the code:
`if a  == None:
    pass
`

prospector shows both:
`[prospector - pylint] 
Comparison to None should be 'expr is None'
 [singleton-comparison]`
and
`[prospector - pep8] 
comparison to None should be 'if cond is None:'
 [E711]`

Also, is there a particular reason why pep8 is included with the package? It seems like pylint covers all the pep8 lints.

**Comment by chocoelho** [comment]
@andrehsu I merged both messages, thanks for noticing that. This should be added to the next release.
