### ISSUE TITLE
Support for more recent pylint

### ISSUE THREAD

**Issue by espenfl** [PyCQA/prospector#319]
Considering this: 
https://github.com/PyCQA/pylint/issues/2435

Please consider to support a more recent version of pylint.

**Comment by chocoelho** [comment]
We are experimenting it in `1.1.7.dev0`, and if all goes well, we can merge #342

**Comment by chocoelho** [comment]
Closing this as prospector 1.1.7 should fix this issue. Feel free to reopen it if this is erroring for you.
