### ISSUE TITLE
Completely ignore `node_modules` directory

### ISSUE THREAD

**Issue by rik** [PyCQA/prospector#328]
Running prospector in a repository that includes `node_modules` is slower than it could be, even with `-i node_modules`.

I've narrowed the issue to `FoundFiles` also including ignored directories and files. It's very easy to get 10,000+ files in `node_modules` and that slows running prospector. On top of slowing the initial file collection, every time `FoundFiles._iter_paths` is called, it has to discard most of the files.

Could we completely bypass this folder?

Here's a few solutions I have in mind for this:
- Hardcode `node_modules`, [just like `.`](https://github.com/PyCQA/prospector/blob/7cfc6d587049a786f935a722d6851cd3b72d7972/prospector/finder.py#L154)
- Include a new option to completely ignore some folders
- Read version control ignore files and take them into account

**Comment by chocoelho** [comment]
You can also use `ignore-paths` or `ignore-pattern` inside your prospector configuration files, although I see reason to have this ignored by default.

**Comment by rik** [comment]
`ignore-paths` and `ignore-pattern` will not reduce the amount of files added to `FoundFiles.files`. It will save them with `ignored=True`.
