### ISSUE TITLE
requirements of prospector 1.1.6.3 and flake8 are contradicting

### ISSUE THREAD

**Issue by feenes** [PyCQA/prospector#332]
Prospector has max versions for following dependencies:
pycodestyle<=2.4.0,>=2.0.0
pyflakes<2.0.0,>=0.8.1

flake8 has min version requirements superior to the max version required by prospector.

Is it really necessary to max limit pycodestyle and pyflakes?

I am asking as this means, that prospector and flake8 cannot coexist (without pip check warnings) in the same virtualenv

In general: Over time max version limits that are not being increased will create more and more conflicts with other python packages.

**Comment by carlio** [comment]
It was necessary at one point due to newer versions of pycodestyle not being API-compatible with prospector but that should be fixed. Similar things keep happening, https://github.com/PyCQA/prospector/issues/307 for example, so we need to do some code tidyup to get proper compatability.

@chocoelho please don't make releases to quickly as we have a lot of these library compatability things to look into and it breaks lots of CI builds.

**Comment by chocoelho** [comment]
Yeah, it was my bad. I tested with a few projects here and it passed, so I gave it a go. @carlio in this case, what was released was just mostly a patch for `pylint-django`.

**Comment by chocoelho** [comment]
But should have opened a PR before

**Comment by AtHeartEngineer** [comment]
FYI, current requirement conflicts I'm having are:
```
prospector 1.1.6.4 has requirement pep8-naming<=0.4.1,>=0.3.3, but you'll have pep8-naming 0.8.2 which is incompatible.
prospector 1.1.6.4 has requirement pycodestyle<=2.4.0,>=2.0.0, but you'll have pycodestyle 2.5.0 which is incompatible.
prospector 1.1.6.4 has requirement pyflakes<2.0.0,>=0.8.1, but you'll have pyflakes 2.1.1 which is incompatible.
prospector 1.1.6.4 has requirement pylint-django==2.0.9, but you'll have pylint-django 2.0.11 which is incompatible.
```
I'm assuming all of those conflicts are the latest stable. Just a heads up, not giving any grief.

**Comment by volans-** [comment]
If I may ask, why there is a strict requirement of `pep8-naming<=0.4.1`? There have been 7 more releases in `pep8-naming` since then and would be nice to be able to have access to newest releases.

**Comment by carlio** [comment]
@volans- I need to go back and have a look but I think there were some breaking changes to `>0.4.1` that either got fixed but we didn't update the dependency pinning or did not get fixed.

**Comment by volans-** [comment]
@carlio ack, thanks for the real-time answer!

**Comment by chocoelho** [comment]
I'm currently working on making both of these tools compatible, so we hope to have this done until next release.

**Comment by chocoelho** [comment]
Closing this issue as it is fixed in the new version of prospector to be released soon
