### ISSUE TITLE
[FEATURE REQUEST] Improve documentation for installation on OSX Catalina (zsh)

### ISSUE THREAD

**Issue by BKrajancic** [PyCQA/prospector#366]
The readme for prospector has instructions to install using command: 
> pip install prospector[with_pyroma] 

On mac OSX catalina, the terminal now uses 'zsh' by default, where brackets need to be escaped. 

I suggest adding to the documentation: 
> On Mac os X Catalina, the default terminal (zsh) require brackets to be escaped. For instance, installing with_pyroma will be:  
> pip install prospector\[with_pyroma\]
 
I'm happy to make a pull request for this change, as it is only for documentation. I think this will be a helpful addition as there are more users switching over to zsh and Catalina.

**Comment by carlio** [comment]
Sure, go ahead and make a PR. Although I couldn't spot the difference between your two examples :-)

**Comment by BKrajancic** [comment]
Closed due to: https://github.com/PyCQA/prospector/commit/a9a993ae7aad28b7ec176119c263596459a0db5a
