### ISSUE TITLE
[BUG] The output-target defined in configuration but never used.

### ISSUE THREAD

**Issue by ccruz09** [PyCQA/prospector#377]
**Describe the bug**
 Prospector allows users to define an 'output-target' in the configuration file which allows them to redirect the reports generated to that defined target. Even though the user defines the output-target, the merge profile internal functionality of the application disregards this configuration item. which prevents users to direct the output to the target location.

**To Reproduce**
1. Go to the configuration file (prospector.yml).
2. Add 'output-target: prospector-report' to the configuration file.
3. Call prospector the following way: prospector --zero-exit **/*.py
4. No file is generated with the prospector's output

**Expected behavior**
A file that contains prospector's output is generated in the location defined by the output-target. 

**Environment (please complete the following information):**
 - OS: [linux, wsl]
 - Tool [pylint, bandit]
 - Prospector version [1.2.0]
- Python version [3.8.2]

**Comment by chocoelho** [comment]
Awesome, self assigned the PR. Should have it reviewed this weekend. Thanks for the contribution.

**Comment by chocoelho** [comment]
Hey there, just release `1.3.0.dev0`. Can you check if this is still the case?

**Comment by ccruz09** [comment]
It worked. It's generating the output file.

**Comment by chocoelho** [comment]
Awesome. There are still some other adjustments to the upgrade of Pylint involved in this new version, but we should have all sorted out by the end of the month so that we can release a stable version.
