### ISSUE TITLE
Support Safety

### ISSUE THREAD

**Issue by medecau** [PyCQA/prospector#379]
Security issues may be found on dependencies.
It would be nice if Prospector could report on known dependency security issues.
Safety uses an open source database of known security issues for Python packages.
https://github.com/pyupio/safety

**Comment by chocoelho** [comment]
That can be considered, though prospector is mostly focused on code linters rather than dependency checking.

**Comment by medecau** [comment]
@chocoelho, I agree.
Further, "Safety" is a product from a company and I'd rather have to call that one product directly.
