### ISSUE TITLE
[BUG] 1.3.0 does not respect pylint-django's migration ignores

### ISSUE THREAD

**Issue by rik** [PyCQA/prospector#381]
Testcase in https://github.com/rik/prospector-pylint-ignore. The instructions to reproduce are in the README

**Comment by chocoelho** [comment]
Thanks, should look at it soon.

**Comment by chocoelho** [comment]
Great @rik, managed to reproduce it. Should take a look at it later today.

**Comment by chocoelho** [comment]
@rik Found the issue, will fix some more updates to release 1.3.0.dev4 soon :) thanks for reporting this

**Comment by chocoelho** [comment]
1.3.0.dev4 released

**Comment by rik** [comment]
Great, that fixed it! Thank you!
