### ISSUE TITLE
[BUG] "noqa" not working on unique enums

### ISSUE THREAD

**Issue by Pathfinder216** [PyCQA/prospector#382]
**Describe the bug**
Prospector with "strictness_high" fails to suppress UPPER_SNAKE_CASE naming warnings for unique enums when a "# noqa" comment is added.

When running in Python 3.6.1 with the "strictness_high" profile, pylint gives the warning and requires a "# noqa" to additionally be placed on the `@unique` line to fully suppress the warning. When running in Python 3.8.3 with the "strictness_high" profile, pep8 gives the warning and requires a "# noqa" to additionally be placed on the line following the class name to fully suppress the warning.

**To Reproduce**
Using foo.py:
```python
from enum import Enum, unique


@unique
class FOO_BAR(Enum):  # noqa
    BAZ = 1
```
Run `prospector foo.py --profile strictness_high`

**Expected behavior**
Adding a "# noqa" comment to the line with the class name should fully suppress the warning.

**Environment**
 - OS: Windows 10, Linux (Debian)
 - Tool: pylint/pep8
 - Prospector version: 1.2.0
 - Python version: 3.6.1/3.8.3

**Comment by chocoelho** [comment]
@Pathfinder216 just added a test case for that, and AFAICT, it's properly ignoring in 1.3.0.dev4.
