### ISSUE TITLE
[BUG] Pre-commit hook not working with Pyroma and Vulture

### ISSUE THREAD

**Issue by jpedroantunes** [PyCQA/prospector#387]
**Describe the bug**
Actually I am trying to use the prospector on git hook. Actually, we are not being able to run Pyroma and Vulture (extra tools) on Git hook. I always receive the following message:
```
Cannot run tool pyroma as support was not installed.
Please install by running 'pip install prospector[with_pyroma]'
```

I can successfully run Prospector through terminal with these tools. The problem only happens when running using Git Hook.

**To Reproduce**
1. Create a pre-commit git hook in your project
Install the pre-commit lib:
```
pip install pre-commit
```
Activate pre-commit in your project root folder:
```
pre-commit install
```
Create a .pre-commit-config.yaml on the project root folder:
```
repos:
    -   repo: https://github.com/PyCQA/prospector
        rev: 1.1.7
        hooks:
            -   id: prospector
```
2. Define a .prospector.yml on the root folder:
```
output-format: grouped

pyroma:
  run: true

vulture:
  run: true
```
3. Commit any python file to activate the hook execution.

**Expected behavior**
I expected that the prospector run fine. But I received the following error for pyroma or vulture:
```
Cannot run tool pyroma as support was not installed.
Please install by running 'pip install prospector[with_pyroma]'
```

**Environment (please complete the following information):**
 - OS: Linux Mint 19
 - Tool: 
 - Prospector version: 1.1.7
- Python version 3.6.9

**Additional context**
When I run the prospector through terminal, everything executes fine. This behavior only happens on Git Hook.

**Comment by carlio** [comment]
This isn't a bug in prospector, more a way that the pre-commit configuration installs the *base* prospector without extras. In your `.pre-commit-config.yaml` you can just install the extra dependencies manually : https://pre-commit.com/#config-additional_dependencies

**Comment by carlio** [comment]
I finally got around to sorting out the pre-commit documentation :-)

I had added the `additional_dependencies` but I was struggling to find a way to use the `with_` syntax to honour the version pinning of prospector rather than having to just say "install latest mypi" so thank you so much @jnydutra for this solution!

The README and the documentation have been updated now.
