### ISSUE TITLE
[BUG] Out of date documentation

### ISSUE THREAD

**Issue by stsewd** [PyCQA/prospector#388]
Looks like builds aren't being triggered at rtd https://readthedocs.org/projects/prospector/builds/, probably you need to update/resync the webhook https://docs.readthedocs.io/en/stable/webhooks.html#resyncing-webhooks

Also, noticed the domain doesn't have a ssl cert, you may want to check https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support

**Comment by carlio** [comment]
Thanks for pointing this out @stdweird I hadn't noticed.

I had never set up the "new" webhooks/services integration. That's done now, but the readthedocs defaults are failing so I'll need to create a specific `.readthedocs.yaml` config file to get it going. I'm on it though :-)

**Comment by carlio** [comment]
Ok, seems to be working now, that was pretty painless!
