### ISSUE TITLE
[BUG] vulture support broken for any release after 0.24

### ISSUE THREAD

**Issue by kormat** [PyCQA/prospector#389]
**Describe the bug**
Prospector passes an invalid keyword argument to vulture's constructor. The `exclude` keyword was removed in vulture 0.25 (https://github.com/jendrikseipp/vulture/commit/d35e73dedaf26c4f4b693760e168a87ef7b72579). This is effectively #230 again. 83df4e33471eddf47f727fedf636564149d36d57 removed the old constraint that was added in eeacd5e192488cc2c4cde9b4a89e99a047779fdc as a workaround:

```
'with_vulture': ('vulture>=0.6,<0.25',),
```
replacing it with:
```
"with_vulture": ("vulture>=1.5",),
```

**To Reproduce**
1. Create fresh venv, install prospector: `pip install prospector[with_vulture]==1.3.0`
1. Create `prospector.yaml` with:
```
vulture:
  run: true
```
2. Run prospector: `prospector --profile prospector.yaml -X .`
3. See error:
```
Traceback (most recent call last):
  File "/home/kormat/tmp/prospector-bug/.direnv/python-3.6.9/bin/prospector", line 8, in <module>
    sys.exit(main())
  File "/home/kormat/tmp/prospector-bug/.direnv/python-3.6.9/lib/python3.6/site-packages/prospector/run.py", line 167, in main
    prospector.execute()
  File "/home/kormat/tmp/prospector-bug/.direnv/python-3.6.9/lib/python3.6/site-packages/prospector/run.py", line 67, in execute
    messages += tool.run(found_files)
  File "/home/kormat/tmp/prospector-bug/.direnv/python-3.6.9/lib/python3.6/site-packages/prospector/tools/vulture/__init__.py", line 72, in run
    vulture = ProspectorVulture(found_files)
  File "/home/kormat/tmp/prospector-bug/.direnv/python-3.6.9/lib/python3.6/site-packages/prospector/tools/vulture/__init__.py", line 10, in __init__
    Vulture.__init__(self, exclude=None, verbose=False)
TypeError: __init__() got an unexpected keyword argument 'exclude'
```

**Expected behavior**
I expected vulture to run successfully.

**Environment (please complete the following information):**
 - OS: linux mint 19.3 (ubuntu 18.04 equiv)
 - Tool: vulture
 - Prospector version: 1.3.0
 - Python version: 3.6.9, 3.7.8

**Additional context**
```
$ pip freeze
astroid==2.4.1
dodgy==0.2.1
flake8==3.8.3
flake8-polyfill==1.0.2
importlib-metadata==1.7.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pep8-naming==0.10.0
prospector==1.3.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
pylint==2.5.2
pylint-celery==0.3
pylint-django==2.0.15
pylint-flask==0.6
pylint-plugin-utils==0.6
PyYAML==5.3.1
requirements-detector==0.7
setoptconf==0.2.0
six==1.15.0
snowballstemmer==2.0.0
toml==0.10.1
typed-ast==1.4.1
vulture==1.5
wrapt==1.12.1
zipp==3.1.0
```

**Comment by kormat** [comment]
I can confirm that 1.3.1.dev1 works correctly. Thanks!

**Comment by chocoelho** [comment]
Great. Should have a stable release soon. Thanks for checking it out.

**Comment by mihnatenko** [comment]
I'm facing the same issue. @chocoelho, is there any ETA for 1.3.1 release?

**Comment by chocoelho** [comment]
@mihnatenko Sorry about the delay. Got so busy that I forgot to do the release. It's now published to Pypi.
