### ISSUE TITLE
Tool pylint failed to run (exception was raised)

### ISSUE THREAD

**Issue by kamil-murtaza** [PyCQA/prospector#401]
I am getting an error in static analysis when I insert __init__.py file in my root directory.If I remove __init__.py file error is resolved but I need __init__.py file.

My project structure is :
api:
  apps:
       module1
       module2
       __init__.py

1. Go to the apps directory
2. Call prospector the following properties : 
 strictness: veryhigh
output-format: pylint
autodetect: false
doc-warnings: true
member-warnings: true
test-warnings: false
max-line-length: 120
ignore-paths:
  - documentation
  - requirements
  - tests
  - migrations
  - build-env
uses:
  - django
vulture:
  run: false
bandit:
  run: true
mccabe:
  options:
    max-complexity: 10
pep8:
  full: true
  disable:
    - E203
pep257:
  disable:
    - D104
    - D203
    - D212
pylint:
  full: true
  disable:
    - relative-beyond-top-level
    - import-outside-toplevel
  options:
    good-names:
      - c
      - e
    ignore: "migrations|tests"

3. Error occured :
    Tool pylint failed to run (exception was raised) error in static analysis.

**Expected behavior**
Pylint should run successfully.

**Environment:**
 - OS: Windows 10
 - Pylint version 2.5.2
 - Prospector version 1.3.0
- Python version 3.8.5

![Screenshot (5)](https://user-images.githubusercontent.com/33691198/104712076-fa60b800-5743-11eb-80be-02f2d0849366.png)

**Comment by abadger1406** [comment]
```
(venv) dave@study:~/beepaid/backend$ prospector --version
prospector 1.3.1
(venv) dave@study:~/beepaid/backend$ pylint --version
pylint 2.5.3
astroid 2.4.1
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
(venv) dave@study:~/beepaid/backend$ uname -a
Linux study 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(venv) dave@study:~/beepaid/backend$ prospector 



```

**Comment by carlio** [comment]
I am doing some tidying up of issues and this is nearly a year old now.

Could you try this with latest prospector and see if you have the same issue?

If you do, please run prospector using the `-X` flag and it will show the stacktrace that pylint raised.

I'll close this but re-open the issue if it's still a problem.
