### ISSUE TITLE
[BUG] - typing are detected as unsubscriptable because embedded pylint version is old

### ISSUE THREAD

**Issue by metal3d** [PyCQA/prospector#409]
**Describe the bug**
Embedded Pylint version is 2.5.3 while there is a 2.6.0. It causes false positives on typing Union and Optional.

See: https://github.com/PyCQA/prospector/blob/master/setup.py#L33

**To Reproduce**
1- create a class or function with `typing.Optional` annotation
e.g.
```python
class User:
    name: Optional[str]
```
2- see prospector output, e.g.:
```
    pylint: unsubscriptable-object / Value 'Optional' is unsubscriptable (col 18)
    pylint: unsubscriptable-object / Value 'Union' is unsubscriptable (col 27)
```

**Expected behavior**
No error

**Environment (please complete the following information):**
 - OS: Linux Fedora 33
 - Tool: pyling
 - Prospector version: 1.3.1
- Python version: 3.9.2

**Additional context**
Installed with pipenv

**Comment by bansan85** [comment]
Please, update to pylint 2.7.0. According to [safety-db](https://github.com/pyupio/safety-db/blob/master/data/insecure_full.json) id 39621, previous version are unsecured.
