### ISSUE TITLE
[BUG] not prospecting file in dir

### ISSUE THREAD

**Issue by bechtold** [PyCQA/prospector#417]
Describe the bug
As I read from the [docs](http://prospector.landscape.io/en/master/index.html#usage) I run `prospector` in the dir with the file and it doesn't check the file. But when I run `prospector example.py` the file is checked. I realized this while creating #416. 

To Reproduce

- Create a file (example.py) with a very long line
- Add # pylint: disable=line-too-long to the beginning of the file
- Call `prospector` to not see any errors
- Call `prospector example.py` to see the expected errors

Expected behavior
File should be checked without specifically calling it.

Environment (please complete the following information):
- OS: macOS Big Sur on M1
- Tool: prospector
- Prospector version 1.3.1
- Python version 3.9.4

**Comment by carlio** [comment]
Please can you see if this is still happening for you with the 1.8.0rc0 release? I just pushed it, it should address this (and other) issues about finding files
