### ISSUE TITLE
[FEATURE REQUEST] Add ``PYPI_API_TOKEN `` in repository secrets

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/prospector#428]
Hello again, @carlio, thanks to your quick intervention this morning, I released version 1.4.0 manually. I also added [a github action](https://github.com/PyCQA/prospector/blob/master/.github/workflows/release.yml) that would permit to release automatically in the future (when creating a tag and releasing on github). I only need the right to add the pypi token in the settings, Or you could add your own token following  yourself :

    Select the Settings tab
    Click the Secrets section in the left hand menu
    Add a new secret and use ``PYPI_API_TOKEN`` after creating a new token on pypi.

It's not a big deal if you don't have the time for that, I'll keep doing it manually :)

Cheers !

**Comment by carlio** [comment]
Done!

**Comment by carlio** [comment]
I created a `1.4.1.1` release just to check it all works - no code has changed, just the version bump so I could validate the CI pipeline.

Also, I have a `1.5.0.dev1` because I'm playing around with converting the project to using poetry for packaging, just FYI

**Comment by Pierre-Sassoulas** [comment]
Amazing ! Moving to poetry sounds great too.

**Comment by Pierre-Sassoulas** [comment]
(The test release you did would have worked if 1.4.1 was not already released)
