### ISSUE TITLE
[BUG] Prospector 1.5.0.1 incompatibility between pyflakes dependency

### ISSUE THREAD

**Issue by adamcunnington-gdt** [PyCQA/prospector#439]
**Describe the bug**
There is an incompatibility between prospector's requirements:

Could not find a version that matches pyflakes<2.3.0,<2.4.0,>=2.2.0,>=2.3.0 (from prospector[with_everything]==1.5.0.1)
There are incompatible versions in the resolved dependencies:
  pyflakes<2.3.0,>=2.2.0 (from prospector[with_everything]==1.5.0.1->...)
  pyflakes<2.4.0,>=2.3.0 (from flake8==3.9.2->flake8-polyfill==1.0.2->pep8-naming==0.10.0->prospector[with_everything]==1.5.0.1->...)

**To Reproduce**
1. `echo "prospector[with_everything]" > requirements.in`
2.  `pip-compile`

You won't run into this issue with pip because pip doesn't attempt to resolve dependency conflicts.

**Expected behavior**
Dependencies should be compatible.

**Comment by sbrunner** [comment]
Isn't fixed with version `1.5.1b0`?

**Comment by adamcunnington-gdt** [comment]
@sbrunner thanks, yep, that fixes

**Comment by carlio** [comment]
Oh yes, this would have been scooped up in `1.5.1b0` since it was already merged into the develop branch :-)  Once that beta release is promoted I'll update the CHANGELOG properly and close this but for now leave it open as the 1.5.0.1 will still be the default for anyone not installing pre-releases

**Comment by okuuva** [comment]
This is now fixed in stable since 1.5.1 came out

**Comment by carlio** [comment]
Thanks @okuuva I forgot to close this one!

**Comment by Pierre-Sassoulas** [comment]
Could you open another issue @adamcunnington-gdt, please ?

**Comment by adamcunnington-gdt** [comment]
https://github.com/PyCQA/prospector/issues/454
