### ISSUE TITLE
[FEATURE REQUEST] Add darglint to prospector

### ISSUE THREAD

**Issue by adamcunnington-gdt** [PyCQA/prospector#449]
[Darglint](https://github.com/terrencepreilly/darglint) has gained a lot of traction recently. It is a functional docstring linter - and is a [nice complement to pydocstyle](https://github.com/terrencepreilly/darglint#scope), already included in Prospector.

Would prospector consider adding this in? It feels like the only gap right now and it's the only linting tool I run additionally to prospector (except for black/isort which are considered a different category; "formatting").

**Comment by Pierre-Sassoulas** [comment]
It does not seem very different than [pylint's docparam checker](https://pylint.pycqa.org/en/latest/technical_reference/extensions.html#pylint-extensions-docparams) that is already in prospector.

**Comment by adamcunnington-gdt** [comment]
Oh cool, I did not know about that - thanks - will use this; closing issue.
