### ISSUE TITLE
[BUG] pyflakes incompatibility caused by flake8

### ISSUE THREAD

**Issue by adamcunnington-gdt** [PyCQA/prospector#454]
**Describe the bug**
flake8 4.0.0 was released and it causes an incompatibility with pyflakes, which prospector requires via pep8-naming

```bash
(.venv) ac@penguin:~/Projects/test$ echo "prospector[with_everything]" > requirements.in
(.venv) ac@penguin:~/Projects/test$ pip-compile
Could not find a version that matches pyflakes<2.4.0,<2.5.0,>=2.2.0,>=2.4.0 (from prospector[with_everything]==1.5.1->-r requirements.in (line 1))
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.4.0, 2.4.0
There are incompatible versions in the resolved dependencies:
  pyflakes<2.5.0,>=2.4.0 (from flake8==4.0.0->flake8-polyfill==1.0.2->pep8-naming==0.10.0->prospector[with_everything]==1.5.1->-r requirements.in (line 1))
  pyflakes<2.4.0,>=2.2.0 (from prospector[with_everything]==1.5.1->-r requirements.in (line 1))
Looks like this was caused by a flake8 (prospector indirectly depends on flake8 via pep8-naming) release 7 hours ago; https://pypi.org/project/flake8/4.0.0/
```

**To Reproduce**
1. Install latest version of prospector[with_everything]
2. Use some tooling that does dependency evaluation (poetry, pip-tools, pipenv etc.)
3. See error

**Expected behavior**
No incompatibility.

**Additional context**
If prospector's dependency of pyflakes was <**=**2.4.0, we'd get away with it.

For now, pinning flake8=3.9.2, alongside prospector, will fix.

**Comment by adamcunnington-gdt** [comment]
I assume that prospector uses pyflakes directly, not just indirectly via flake8 so I don't see how you could avoid pinning a dependency - but you do need to maintain compatible pinning with flake8.

Changing pyflakes dependency (to <= 2.4.0) would fix it right now but it's probably a bit shortsighted given flake8 is narrowly supporting only 2.4.0 (inclusive) - 2.5.0 (exclusive).

**Comment by Pierre-Sassoulas** [comment]
We might indeed need to adapt [this file](https://github.com/PyCQA/prospector/blob/master/prospector/tools/pyflakes/__init__.py) to the version of the latest flake8 regularly. It might not be a lot of work but a check needs to be done. Could be done by the pre-commit bot and our tests suite though. So if tests do not break then the upgrade is automated.

**Comment by adamcunnington-mlg** [comment]
Any movement on this?

**Comment by Pierre-Sassoulas** [comment]
No, do you want to contribute to the issue ?

**Comment by figure002** [comment]
I use pip-tools and confirm that pinning `flake8 == 3.9.2` fixes it for now.

**Comment by camilonova** [comment]
@Pierre-Sassoulas which file of flake8 are you referring to? I think I can make the update manually for now, while we figure out how to make it automatically.
https://github.com/PyCQA/flake8/tree/main/src/flake8

**Comment by Pierre-Sassoulas** [comment]
I meant this one in prospector : https://github.com/PyCQA/prospector/blob/master/prospector/tools/pyflakes/__init__.py (there's a link in my previous comment)

**Comment by camilonova** [comment]
@sbrunner this means it was fixed?

**Comment by sbrunner** [comment]
Yes, for me, it's fixed :-)
