### ISSUE TITLE
[BUG] prospector should warn about unknown options

### ISSUE THREAD

**Issue by rnestler** [PyCQA/prospector#455]
**Describe the bug**
If I have a typo in my configuration options (or try to use an unexisting option), I'd expect that prospector raises a warning or an error.

To find out how to configure mypy I had to look at the source at https://github.com/PyCQA/prospector/blob/master/prospector/tools/mypy/__init__.py until I found out that I need to do
```yaml
mypy:
  options:
    warn:
      - unreachable
```
Instead of
```yaml
mypy:
  options:
    warn-unreachable: true
```

**To Reproduce**
1. Add an unexisting option to `.prospector.yaml`
2. Run prospector
3. prospector just ignores it

**Expected behavior**
Prospector should warn or raise an error

**Environment (please complete the following information):**
 - OS: Linux
 - Tool mypy
 - Prospector version 1.5.1
- Python version 3.8.10

**Additional context**
It would have helped me enormously if there was a verbose or debug mode, where I could see how exactly mypy gets called.

**Comment by AtomScott** [comment]
I'm having a lot of trouble configuring mypy. I think warning about unknown options would be a good idea. The docs need to be more exhaustive too.

How would one go implement such warnings?

**Comment by carlio** [comment]
I'm not familiar with mypy nor did I write the tool so I'm not 100% sure what each of the options do. However, I have added an exception which is raised if an option is not recognised, along with a unit test to validate it: https://github.com/PyCQA/prospector/commit/c163370212e44e010015575dd4b81b153394f14a

@AtomScott or others, if you would like to improve the documentation and add more robust testing for other value parsing issues in the mypy tool, please go ahead and raise a PR. The commit above should help point you at the right place to start, but if you have questions please ask!

**Comment by sbrunner** [comment]
Are you sure that the list is exhaustive?
In the documentation I see many options starting with e.g. warn-* that's not in the list...
https://mypy.readthedocs.io/en/stable/command_line.html#configuring-warnings
