### ISSUE TITLE
[FEATURE REQUEST] Shareable profile

### ISSUE THREAD

**Issue by NoamNol** [PyCQA/prospector#459]
I want to share a profile of my organization and let people easily inherit it in their projects.

In ESLint there is the [Shareable Config](https://eslint.org/docs/developer-guide/shareable-configs) - just install the organization package and inherit ("extend") the config.

**Comment by carlio** [comment]
@NoamNol Have you seen that profiles can already inherit from each other? http://prospector.landscape.io/en/master/profiles.html#inheritance

And if so, could you help me explain how what you need is different to what is supported?

Aside from adding a URL to a profile (which would be cool by itself) are there other things you're asking for?

**Comment by NoamNol** [comment]
@carlio  URL is cool but it's not the best option when working offline.
No, what I want is the same as ESLint did:

1. `pip install niceprofile`
2. in my profile, inherits `niceprofile`

Now I can control the exact profile version I inherited (requirements.txt, poetry...).
And you can add a naming convention (like ESLint): `prospector-profile-niceprofile`

**Comment by sbrunner** [comment]
This can easily be done by using this function:
https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data
and we can use the syntax `<module>:<filename>`
If you agree I can probably do a pull request :-)

**Comment by NoamNol** [comment]
@sbrunner This is nice, 
maybe we want to agree on a default name for the profile file, and only use the module name without the file name.
In eslint the default name is index.js

**Comment by carlio** [comment]
Prospector already has a list of profile names it'll load by default if they're in the cwd - https://github.com/PyCQA/prospector/blob/master/prospector/profiles/__init__.py#L3 - so I'd suggest using one of those

**Comment by NoamNol** [comment]
And we need to decide on a naming convention. 
I think shareable profile packages must start with `prospector-profile-` or `prospector-prof-`, 
which one do you prefer?

**Comment by sbrunner** [comment]
I prefer `prospector-profile-` 
And what about `index.yaml` as default file name?

**Comment by NoamNol** [comment]
I think `prospector.yaml` is the most appropriate.

**Comment by NoamNol** [comment]
@sbrunner Thanks!
