### ISSUE TITLE
Upgrade pylint to 2.12.2 to accommodate fix to docparams ext

### ISSUE THREAD

**Issue by adamcunnington-mlg** [PyCQA/prospector#466]
Please can you upgrade pylint to latest stable version (2.12.2) to accommodate fix to docparams ext, during next release? Thanks

**Comment by carlio** [comment]
Hello - that is the plan - see https://github.com/PyCQA/prospector/issues/465#issuecomment-982376728

It's on the TODO list, no worries.

**Comment by adamcunnington-mlg** [comment]
Ah thanks, will close this one.

**Comment by carlio** [comment]
@adamcunnington-mlg can you please try with prospector version `1.5.3.dev0`? That should work fine, it's still just a pre-release while people can test it.

**Comment by adamcunnington-mlg** [comment]
@carlio it looks like 1.5.3 was released but no, this doesn't solve the issue. pyproject.toml is still pinning pylint as < 2.12 - we need 2.12

**Comment by carlio** [comment]
oops, I forgot about that. It was pinned to avoid downloading a pylint version that prospector didn't work with. Thanks for letting me know, I'll make a new release without that pin.

Sorry!

**Comment by carlio** [comment]
@adamcunnington-mlg done - `1.5.3.1` is on PyPI
