### ISSUE TITLE
[BUG] Broken links in docs

### ISSUE THREAD

**Issue by RinatVeliakhmedov-TomTom** [PyCQA/prospector#473]
**Describe the bug**
Broken link in the documentation:
http://prospector.landscape.io/en/master/profiles.html#tool-options
in the line `See mypy options for more details See bandit options for more details` both links are broken:
`https://https//bandit.readthedocs.io/en/latest/config.html`
`https://https//bandit.readthedocs.io/en/latest/config.html`

**To Reproduce**
1. Go to http://prospector.landscape.io/en/master/profiles.html#tool-options
2. Click the `mypy options` or `bandit options` link.

**Comment by carlio** [comment]
Finally fixed this - turns out documentation was not being generated since version 1.5 :fearful:
