### ISSUE TITLE
[BUG] pylint w0614 combine exception

### ISSUE THREAD

**Issue by stdweird** [PyCQA/prospector#477]
**Describe the bug**
Pylint now has new ways of merging wildcard import errors since https://github.com/PyCQA/pylint/pull/5110 was merged. Now the regex in https://github.com/PyCQA/prospector/blob/master/prospector/tools/pylint/__init__.py#L235 has no match, and raises an exception

```
    prospector.execute()
  File "/some/path/workspace/.eggs/prospector-1.5.3.1-py3.6.egg/prospector/run.py", line 69, in execute
    messages += tool.run(found_files)
  File "/some/path/workspace/.eggs/prospector-1.5.3.1-py3.6.egg/prospector/tools/pylint/__init__.py", line 262, in run
    return self.combine(messages)
  File "/some/path/workspace/.eggs/prospector-1.5.3.1-py3.6.egg/prospector/tools/pylint/__init__.py", line 254, in combine
    combined = self._combine_w0614(messages)
  File "/some/path/workspace/.eggs/prospector-1.5.3.1-py3.6.egg/prospector/tools/pylint/__init__.py", line 235, in _combine_w0614
    names.append(_UNUSED_WILDCARD_IMPORT_RE.match(msg.message).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

```

**To Reproduce**
2. Call prospector the following way '....'
3. See error

**Expected behavior**
non-matching group exception is handled. 
ideally detecting this is an already merged message?

**Environment (please complete the following information):**
 - OS: [e.g. macOS] linux
 - Tool [e.g. pylint] pylint
 - Prospector version [e.g. 1.1.7] 1.5.3.1
- Python version [e.g. 3.6.8] 3.6.9

**Additional context**

**Comment by thburghout** [comment]
Confirmed. The regex should be 
```
_UNUSED_WILDCARD_IMPORT_RE = re.compile(r"^Unused import\(s\) (.*) from wildcard import")
```

**Comment by Pierre-Sassoulas** [comment]
@thburghout I would merge a fix for this if you want to open a merge request :)

**Comment by carlio** [comment]
I've added this fix onto the master branch, thanks for the investigation and regex :-)  I'll go out with the 1.7.1 release
