### ISSUE TITLE
[BUG] `summary-only` and `messages-only` flags on `.prospector.yaml` not taken into account running pre-commit

### ISSUE THREAD

**Issue by pfernandesviz** [PyCQA/prospector#484]
**Describe the bug**
The flags `summary-only` and `messages-only` defined on a `.prospector.yaml` file are not taken into account running `pre-commit`.

**To Reproduce**
1. Add `messages-only: true` in a `.prospector.yaml`
2. Add prospector as a pre-commit hook
3. Run pre-commit like: `pre-commit run prospector --files [...]`
4. See that summary is present

Also happens with `summary-only`.

**Expected behavior**
The flags should work as expected defined in `.prospector.yaml`.

**Environment:**
 - OS: macOS Monterey 12.0.1
 - Tool: prospector/pre-commit
 - Prospector version: 1.6.0
 - Python version 3.7.9

**Comment by carlio** [comment]
`--summary-only` and `--messages-only` are not options which can be added to a profile.

They are CLI only options - they affect display, profiles are about changing what messages are generated.

I've added proper documentation to explain how to use the pre-commit hooks here - https://prospector.landscape.io/en/master/pre-commit.html

(Also had to fix up a couple of things with the pre-commit hook!)
