### ISSUE TITLE
Pylint configuration in pyproject.toml is ignored

### ISSUE THREAD

**Issue by noctuid** [PyCQA/prospector#485]
Currently, prospector seems to ignore any pylint configuration in the pyproject.toml file. For example, I have `fixme` and `invalid-name` disabled in the pyproject.toml. `poetry run pylint` shows no errors, but `poetry run prospector --profile custom` (with a profile that sets strictness none so these pylint errors are enabled by default) still shows `fixme` and `invalid-name` errors. If I use a `.pylintrc`, the errors go away, but I'd rather just configure everything in the pyproject.toml file.

I'm not sure how prospector is running pylint, but it would be nice if it could support pyproject.toml configuration by default.

**Comment by Pierre-Sassoulas** [comment]
What is happening if you're launching pylint directly ? Does it detect the ``pyproject.toml`` (it should in latest version) ? If not what happen when using the ``--rcfile`` option ?

**Comment by noctuid** [comment]
If I launch pylint directly in a module that has a pyproject.toml, it detects it and works fine.

- Run `poetry run pylint <module name or file>` in module directory that contains a pyproject.toml -> works
- Run `poetry run pylint <module name or file>` in module's parent directory that contains a pyproject.toml (but module directory does not) -> does not work (not sure why this is)
- Run `poetry run pylint --rcfile ./pyproject.toml <module name or file>` in same situation as above - works

`poetry run prospector` does not seem to work regardless of which directory I run it in or which directory I put the pyproject.toml. I have to manually specify `--pylint-config-file pyproject.toml` for it to work.

**Comment by carlio** [comment]
Fix merged onto `master` branch, will go out in next 1.7.1 release shortly

**Comment by noctuid** [comment]
On 1.7.6, I still have to manually specify the config file path for both of the situations I specified above (repo root with pyproject.toml or module directory with pyproject.toml). Not sure if this has anything to do with running prospector through poetry. Any ideas?
