### ISSUE TITLE
[BUG] --no-style-warnings option stopped working in 1.7.0

### ISSUE THREAD

**Issue by f11r** [PyCQA/prospector#488]
It  looks like the `--no-style-warnings` option stopped working in the newest release. It's still working in 1.6.0 but after upgrading to 1.7.0 we're now getting pycodestyle errors. It's probably related to the renaming from `pep8` to `pycodestyle`?

**Comment by carlio** [comment]
@f11r you're probably right - can you post your configuration? Either the prospector profile or the command line arguments you are using?

**Comment by carlio** [comment]
@f11r As a workaround, I think if you create a `.prospector.yml` file with the contents:

```
pycodestyle:
  run: false
```

This should get you the old behaviour with `1.7`. Or just pin to `<1.7` and keep the old version.

I'll look into what happened but I think trying to be backwards compatible added an edge case. I'll create a bugfix release when I have one!

**Comment by carlio** [comment]
Fixed on master branch, will go out in a 1.7.1 release soon(ish)

**Comment by f11r** [comment]
@carlio Great to see this getting fixed so quickly :raised_hands:
