### ISSUE TITLE
[BUG] The pylint config from the prospector config file is no more working

### ISSUE THREAD

**Issue by sbrunner** [PyCQA/prospector#492]
**Describe the bug**
With prospector >= 1.7.0 this config as no more effect:
```yaml
pylint:
  disable:
    - too-many-arguments
    - missing-module-docstring
```

**To Reproduce**
1. Go to project directory, e.g.: https://github.com/sbrunner/bashcolor
2. Call prospector the following way `prospector --output=pylint bashcolor`
3. See error
```
************* Module bashcolor
bashcolor/__init__.py:1: [missing-module-docstring(pylint), None] Missing module docstring
bashcolor/__init__.py:39: [too-many-arguments(pylint), colorize] Too many arguments (7/5)
```

**Expected behavior**
The related checks should be disabled

**Screenshots**
https://github.com/sbrunner/bashcolor/runs/5354870714?check_suite_focus=true

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Tool: pylint
 - Prospector version: 1.7.2
- Python version: 3.8.10

**Comment by carlio** [comment]
@sbrunner Could you check with 1.7.3 which was released about 10 minutes ago? It might fix it, but probably not. I'll look into this.

**Comment by carlio** [comment]
Never mind, just tried it myself with 1.7.3 and the problem is there too.

**Comment by carlio** [comment]
@sbrunner @mdabrowski1990 I have just pushed release 1.7.4 to PYPI which should fix this

Could you try it out please and let me know?

I was able to reproduce the problem on your repo @sbrunner, and then test that the fixed worked, so I'm fairly sure but please let me know if not.

I'll leave this bug open for a while for anyone who searches for the same issue.

Short version: don't use 1.7.2 or 1.7.3!

**Comment by carlio** [comment]
Thanks @mdabrowski1990 :-)  And I have yanked 1.7.2 and 1.7.3 for that reason.

**Comment by sbrunner** [comment]
Yes it's working, thanks :-)
