### ISSUE TITLE
[BUG] Could not find a version that matches mccabe - Version mismatches via pip-compile

### ISSUE THREAD

**Issue by va1ha11a** [PyCQA/prospector#515]
**Describe the bug**
Could not find a version that matches mccabe - Version mismatches via pip-compile

**To Reproduce**
1. create a requirements.in with prospector
2. run pip-compile on that .in file

**Expected behavior**
Successful compile of requirements.txt

**Screenshots**
![image](https://user-images.githubusercontent.com/338046/182257734-a97830a1-f3a6-41df-b019-d31ee25ef0f4.png)

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11 (Container)
 - Tool mccabe/flake8-polyfill/flake8
 - Prospector version 1.7.7
- Python version 3.9.12

**Additional context**
Able to work around by pinning as below:
flake8==4.0.1
Noted flake8 5 released a few days back, I guess its related to a mismatch with that.

mccabe 0.7 was released a while back but is not allowed by prospector, would testing /allowing this resolve it?

**Comment by patleeman** [comment]
I ran into this issue while installing 1.7.7. I'm using pipenv so I needed to pin the following dependencies to get it to lock:

```
mccabe = "==0.6.1"
flake8 = "==4.0.1"
```

**Comment by gopackgo90** [comment]
> I ran into this issue while installing 1.7.7. I'm using pipenv so I needed to pin the following dependencies to get it to lock:
> 
> ```
> mccabe = "==0.6.1"
> flake8 = "==4.0.1"
> ```

flake8 4.0.1 already requires mccabe < 0.7.0, so that first pin isn't necessary.

**Comment by Pierre-Sassoulas** [comment]
I would merge a pull request fixing the dependencies. (Would it be possible to make flake8 > 5 work too by  setting flake8 before pylint ?).

**Comment by okuuva** [comment]
1.7.8 release in sight? I know it's fixed in master but people usually run a specific version rather than pinning a commit hash.

**Comment by Pierre-Sassoulas** [comment]
@carlio, can I release 1.7.9 ? (I see some work on 1.8 rc I don't want to step on your toes)
