### ISSUE TITLE
[FEATURE REQUEST] Support for Python 3.11

### ISSUE THREAD

**Issue by cclauss** [PyCQA/prospector#524]
**Is your feature request related to a problem? Please describe.**

I am always frustrated when a new version of Python ships but my favorite tools are yet not compatible with it.
* https://devguide.python.org/versions
* https://www.python.org/download/pre-releases
* PyCQA/pylint#5920

**Describe the solution you'd like**

[Python 3.11 release candidate 2](https://www.python.org/download/pre-releases) is tested and passes on this repo's continuous integration system.

**Describe alternatives you've considered**

**Additional context**

**Comment by Pierre-Sassoulas** [comment]
Blocked by https://github.com/PyCQA/pylint/pull/6551 which itself is blocked by https://github.com/uqfoundation/dill/milestone/17

**Comment by Pierre-Sassoulas** [comment]
I created a MR : #532 

Some tests do not work, any help would be appreciated.

**Comment by cclauss** [comment]
* https://docs.python.org/3.11/whatsnew/3.11.html#pathlib

Also,
> Removed the [__class_getitem__()](https://docs.python.org/3.11/reference/datamodel.html#object.__class_getitem__) method from [pathlib.PurePath](https://docs.python.org/3.11/library/pathlib.html#pathlib.PurePath), because it was not used and added by mistake in previous versions. (Contributed by Nikita Sobolev in [bpo-46483](https://bugs.python.org/issue?@action=redirect&bpo=46483).)

**Comment by Pierre-Sassoulas** [comment]
Closed by #543
