### ISSUE TITLE
[BUG] Updated 1.8.0 rc release

### ISSUE THREAD

**Issue by stdweird** [PyCQA/prospector#527]
**Describe the bug**
Issues with deps in rc1 when using setuptools and prospector as a dependency. Also `prospector.message.Message` is missing `as_dict` in rc1 release (cfr 1.7.7). 

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: linux 
 - Tool : when using prospector as a (test) dependency
 - Prospector version: 1.8.0rc1
- Python version: 3.10

**Additional context**

**Comment by Pierre-Sassoulas** [comment]
Fixed recently, 1.8.0 should fix that.
