### ISSUE TITLE
Cannot install both prospector v1.7.7 and autopep8 v2.0.0

### ISSUE THREAD

**Issue by rittneje** [PyCQA/prospector#528]
Currently we cannot install both prospector v1.7.7 and autopep8 v2.0.0 due to a an incompatibility in their pycodestyles dependency. This was fixed in #516 but there has been no release since then. v1.8.0 has been a release candidate for over 8 months but does not include this fix.

When will a version of prospector with that fix be released?

**Comment by Pierre-Sassoulas** [comment]
Will be released in 1.8.0, which got a lot easier when #536 was merged.
