### ISSUE TITLE
[BUG] pip-compile fails due to pinned pyflakes

### ISSUE THREAD

**Issue by gopackgo90** [PyCQA/prospector#550]
**Describe the bug** When using pip-compile to manage concrete dependencies, when prospector is used pip-compile fails due to flake8 6.

**To Reproduce** Steps to reproduce the behavior:

1. Install pip-tools in a virtual environment
2. Make a requirements.in file that contains only prospector
3. Execute pip-compile
5. See error
```
$ pip-compile requirements.in 
WARNING: using legacy resolver is deprecated and will be removed in future versions. The default resolver will be change to 'backtracking' in 7.0.0 version. Specify --resolver=backtracking to silence this warning.
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches pyflakes<3,<3.1.0,>=2.2.0,>=3.0.0 (from prospector==1.8.2->-r requirements.in (line 1))
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.4.0, 2.4.0, 2.5.0, 2.5.0, 3.0.0, 3.0.0, 3.0.1, 3.0.1
There are incompatible versions in the resolved dependencies:
  pyflakes<3.1.0,>=3.0.0 (from flake8==6.0.0->flake8-polyfill==1.0.2->pep8-naming==0.10.0->prospector==1.8.2->-r requirements.in (line 1))
  pyflakes<3,>=2.2.0 (from prospector==1.8.2->-r requirements.in (line 1))
```

**Expected behavior** pip-compile should produce a set of concrete dependencies successfully.

**Environment (please complete the following information):**

- OS: maOS
- Tool flake8/pyflakes
- Prospector version 1.8.2
- Python version 3.9.15

**Comment by Pierre-Sassoulas** [comment]
flake8  > 6 removed python 3.7 support before it's official end of life and pyflake > 3 removed python 2 style typing as comment so we probably need to release a major if we want to authorize those two. (and prospector should ask for flake8 < 6).
