### ISSUE TITLE
[BUG] Prospector 1.8 does not respect noqa comments

### ISSUE THREAD

**Issue by chatne** [PyCQA/prospector#557]
After upgrading from 1.7 to 1.8, prospector does not respect `noqa`-comments anymore.

### How to reproduce

Create an example file to test, `example.py`:
```python3
testVarible = 1

def a():
    pass
```

Then use Docker to test with both 1.7.7 and 1.8.2 prospector versions:
```bash
# Note that pylint version is set here due to https://github.com/PyCQA/prospector/issues/539
docker run --rm --workdir /usr/src/app -v $(pwd):/usr/src/app python:3.11 bash -c \
    "pip install prospector==1.7.7 pylint==2.14.5 && prospector --strictness high example.py"
```
```bash
docker run --rm --workdir /usr/src/app -v $(pwd):/usr/src/app python:3.11 bash -c \
    "pip install prospector==1.8.2 && prospector --strictness high example.py"
```
There should be 4 errors in both cases:
```
example.py
  Line: 1
    pycodestyle: N816 / variable 'testVarible' in global scope should not be mixedCase (col 2)
    pylint: invalid-name / Constant name "testVarible" doesn't conform to UPPER_CASE naming style
  Line: 3
    pycodestyle: E302 / expected 2 blank lines, found 1 (col 1)
    pylint: invalid-name / Function name "a" doesn't conform to snake_case naming style
```

Now add `noqa` comments
```python3
testVarible = 1  # noqa

def a():  # noqa
    pass
```
And rerun both Docker commands above.

There is 0 errors for 1.7.7, as expected.
With 1.8.2, there are 3 errors for some reason:
```
example.py
  Line: 1
    pylint: invalid-name / Constant name "testVarible" doesn't conform to UPPER_CASE naming style
  Line: 3
    pycodestyle: E302 / expected 2 blank lines, found 1 (col 1)
    pylint: invalid-name / Function name "a" doesn't conform to snake_case naming style
```
Whats going on here?

Versions 1.8.0rc0, 1.8.0rc1, 1.8.1 and 1.8.2 all behave the same way. So something changed between 1.7.7 and 1.8.0rc0.

**Comment by hugoboos** [comment]
Same here. Did some digging.

`get_suppressions` in `suppression.py` returns `lines_to_ignore`. Before 1.8 the key was a `str` and now it is a `Path` object.

In `postfilter.py` on line 46, the path is checked if it is in the dict: `if relative_message_path in lines_to_ignore:`. There is no match, and thus the error is not suppressed.

Using Python 3.11 on arm64

**Comment by hugoboos** [comment]
Caused by this change: https://github.com/PyCQA/prospector/compare/1.7.7...1.8.0#diff-df4d4aafd70e3e43164c4f811e953de61c808b19d96616371ada4e336d8d05ceR51

**Comment by PetrDlouhy** [comment]
Seems to be still present in `1.8.3`. @hugoboos The link may not work as expected - were you able to pinpoint exact commit that caused this? I am not able to determine it from the link.

**Comment by Pierre-Sassoulas** [comment]
There's no commit to revert, but something need to be done differently:

> get_suppressions in suppression.py returns lines_to_ignore. Before 1.8 the key was a str and now it is a Path object.

> In postfilter.py on line 46, the path is checked if it is in the dict: if relative_message_path in lines_to_ignore:. There is no match, and thus the error is not suppressed.

**Comment by stevenxxiu** [comment]
Here's a bit of a hack fix for people who can't stand this now, and don't want to downgrade all their projects.

Update `~/.cache/pre-commit/*/py_env-python3.10/lib/python3.10/site-packages/prospector/postfilter.py`:

```diff
diff --git a/prospector/postfilter.py b/prospector/postfilter.py
index 17821e3..32840df 100644
--- a/prospector/postfilter.py
+++ b/prospector/postfilter.py
@@ -43,8 +43,8 @@ def filter_messages(filepaths: List[Path], messages: List[Message]) -> List[Mess
             continue
 
         # some lines are skipped entirely by messages
-        if relative_message_path in lines_to_ignore:
-            if message.location.line in lines_to_ignore[relative_message_path]:
+        if Path(message.location.path) in lines_to_ignore:
+            if message.location.line in lines_to_ignore[Path(message.location.path)]:
                 continue
 
         # and some lines have only certain messages explicitly ignored
```

I say hack here, as the underlying problem isn't fixed. For a proper fix, `message.location.path` and all the `str` paths should be converted into `Path`.

**Comment by hugoboos** [comment]
@PetrDlouhy This is the commit: https://github.com/PyCQA/prospector/commit/d5f2650960a75dbffeca705d1a7fc881fcce8a60#diff-51603482e3438c4ab022ddb0ac4a828433c510119fbb651ae59317d99e58d62e

**Comment by chatne** [comment]
`1.9.0` fixes this issue.

Pull https://github.com/PyCQA/prospector/pull/580 seems to do the trick. Thanks @christokur!
