### ISSUE TITLE
[BUG] Documentation URL is still not working...

### ISSUE THREAD

**Issue by goldstein0101** [PyCQA/prospector#568]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

2. Call prospector the following way '....'
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- OS: [e.g. macOS]
- Tool [e.g. pylint]
- Prospector version [e.g. 1.1.7]
- Python version [e.g. 3.6.8]

**Additional context** Add any other context about the problem here. Putting the list of
dependencies installed, e.g. the output of `pip freeze` also helps.

**Comment by Pierre-Sassoulas** [comment]
Please don't spam us, #565 was enough.
