### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stolikvo** [PyCQA/prospector#578]
Error message: pylint: failure / Tool pylint failed to run

happens with pylint version 2.15.10

due to a bug in this code:
prospector/tools/pylint/linter.py", line 40, in _expand_files

where the next condition will be "Flase" for version "2.15.10" and above:

if pylint_version > "2.15.6":

**To Reproduce** Steps to reproduce the behavior:

1. Run prospector with pylint version 2.15.10

**Expected behavior** Pylint should be executed

**Environment (please complete the following information):**

- OS: macOS
- Tool pylint - 2.15.10
- Prospector version 1.8.3
- Python version 3.9.6

**Additional context** Add any other context about the problem here. Putting the list of
dependencies installed, e.g. the output of `pip freeze` also helps.

**Comment by Pierre-Sassoulas** [comment]
1.8.4 was released with a fix for this
