### ISSUE TITLE
Bunch of import errors when using prospector v1.8.4 via pre-commit hook

### ISSUE THREAD

**Issue by eugene-kostrov** [PyCQA/prospector#587]
**Describe the bug** If I set `rev: v1.8.4` in `.pre-commit-config.yaml` the prospector task starts to warn about import errors (via pylint's import-error message). There were no such errors for `v1.8.3` (though there were some other problems - #586 ). If I run the prospector manually - no such issues appear
**To Reproduce** Steps to reproduce the behavior:

`.pre-commit-config.yaml`
```
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/prospector
    rev: v1.8.4
    hooks:
    -   id: prospector
```
2. Call prospector the following way `pre-commit run --all-files`

**Expected behavior** Take an information about currently installed packages from the local env instead of receiving bunch of `import-error` errors like this:

```
inference/algorithm/prediction.py
  Line: 1
    pylint: import-error / Unable to import 'numpy'

inference/algorithm/aggregator.py
  Line: 4
    pylint: import-error / Unable to import 'pandas'

```

**Environment (please complete the following information):**

- OS: macOS
- Tool [dodgy, mccabe, profile-validator, pycodestyle, pyflakes, pylint]
- Prospector version 1.8.4
- Python version 3.8.15

**Additional context** 
pre-commit 3.0.2

**Comment by Pierre-Sassoulas** [comment]
Did you install your dependencies for pylint in the pre-commit env with the ``additional_dependencies`` option ?

**Comment by eugene-kostrov** [comment]
No, I have pretty lot of them in multiple requirements files. Should I? Is this some breaking change since 1.8.3 (I did not face any `import-errors` using that version)?

**Comment by Pierre-Sassoulas** [comment]
pre-commit create a separate env with prospector and pylint installed in it, and pylint needs all dependencies installed in this env to work properly so I don't know how it was working before with 1.8.3 (?). But the import error seems to indicate that pylint can't find the dependencies in the env it's installed in.

**Comment by eugene-kostrov** [comment]
Understood, thank you. In case anyone needs it - I was able run it with such config:
```
-   repo: local
    hooks:
    -   id: prospector
        name: prospector
        entry: prospector
        language: system
        types: [python]
        require_serial: true
```
