### ISSUE TITLE
[BUG] Django not available error when running with pre-commit hook

### ISSUE THREAD

**Issue by avinashs2401** [PyCQA/prospector#606]
**Describe the bug** 
In my Django project, I have configured prospector. It works fine when it is run in standalone way. But with pre-commit hook, it's unable to detect some django specific lines and complains like below,
```
Messages
========

polls/models/choice.py
  Line: 1
    pylint: import-error / Unable to import 'django.db'
  Line: 6
    pycodestyle: E303 / too many blank lines (3) (col 1)

pylint_django
  Line: 1
    pylint: django-not-available / Django is not available on the PYTHONPATH
```

**To Reproduce** 

1. Go to Django project root directory
2. Create `.pre-commit-config.yaml` ([pre-commit-config.yaml.txt](https://github.com/PyCQA/prospector/files/11108786/pre-commit-config.yaml.txt))
3. Run `pre-commit install`
4. Make some changes and do `git add .` and `git commit`
5. Receive errors like - `pylint: django-not-available / Django is not available on the PYTHONPATH`

**Expected behavior** 
Linting should happen without issues on pre-commit

**Environment (please complete the following information):**
- OS: macOS
- Tool: pycodestyle
- Prospector version - 1.9.0
- Python version - 3.9.9
- Django - 4.1.7

**Additional context** 
[requirements.txt](https://github.com/PyCQA/prospector/files/11108808/requirements.txt)

**Comment by Pierre-Sassoulas** [comment]
Could you try using ``additional_dependencies`` to install django in the pre-commit environnement ?

**Comment by avinashs2401** [comment]
@Pierre-Sassoulas Ah thank you. I added django in additional_dependencies and it now works!.

**Comment by avinashs2401** [comment]
@Pierre-Sassoulas After the prospector is passed successfully during the pre-commit, the commit screen doesn't come up, it just stops. Any idea on this?
![Screenshot 2023-03-30 at 3 36 25 PM](https://user-images.githubusercontent.com/75415495/228802911-9da990ae-25e6-456c-af08-8cd763caf6cb.png)

**Comment by Pierre-Sassoulas** [comment]
I think the error message is orange is telling you why.
