### ISSUE TITLE
[BUG] prospector keeps asking for install, even though it is already installed

### ISSUE THREAD

**Issue by DaniBodor** [PyCQA/prospector#614]
**Describe the bug** A clear and concise description of what the bug is.

Whenever I try to run prospector it keeps asking to install prospector, even though it is installed already (prospector 1.10.0 and pyroma 4.2).

I've tried:
- reinstalling it using command above (it just says that all requirements are already met)
- uninstall both prospector and pyroma, and then run the pip install
- create a fresh env and only install prospector/pyroma
- trying above options on different repos and with either 

In all cases, it just keeps returning:
> Cannot run tool pyroma as support was not installed.
> Please install by running 'pip install prospector[with_pyroma]'

For at least one of the envs/repos I tried, it was running fine a couple of weeks ago, but now not anymore (despite no new installs into the env). Not sure when it stopped working exactly, because I discovered the problem on a new env/repo and then tested on the other one as well and had same problem.

**To Reproduce** Steps to reproduce the behavior:

create fresh env and try running prospector
1. `conda activate`
1. `conda create -n testenv python=3.9`
1. `conda activate testenv`
1. `pip install prospector[with_pyroma]`
1. `prospector`

**Expected behavior** A clear and concise description of what you expected to happen.
prospector runs on the repo I am currently in

**Screenshots** If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- OS: [WSL: Ubuntu 20.04]
- Tool [prospector]
- Prospector version [1.10.0 / pyroma version 4.2]
- Python version [3.9 and 3.11]

**Additional context** Add any other context about the problem here. Putting the list of
dependencies installed, e.g. the output of `pip freeze` also helps.

pip freeze output:

> astroid==2.15.4
> build==0.10.0
> certifi==2023.5.7
> charset-normalizer==3.1.0
> dill==0.3.6
> docutils==0.20
> dodgy==0.2.1
> flake8==5.0.4
> flake8-polyfill==1.0.2
> gitdb==4.0.10
> GitPython==3.1.31
> idna==3.4
> isort==5.12.0
> lazy-object-proxy==1.9.0
> mccabe==0.7.0
> packaging==23.1
> pep8-naming==0.10.0
> platformdirs==3.5.1
> prospector==1.10.0
> pycodestyle==2.9.1
> pydocstyle==6.3.0
> pyflakes==2.5.0
> Pygments==2.15.1
> pylint==2.17.4
> pylint-celery==0.3
> pylint-django==2.5.3
> pylint-flask==0.6
> pylint-plugin-utils==0.7
> pyproject_hooks==1.0.0
> pyroma==4.2
> PyYAML==6.0
> requests==2.30.0
> requirements-detector==1.2.1
> semver==3.0.0
> setoptconf-tmp==0.3.1
> smmap==5.0.0
> snowballstemmer==2.2.0
> toml==0.10.2
> tomli==2.0.1
> tomlkit==0.11.8
> trove-classifiers==2023.5.2
> typing_extensions==4.5.0
> urllib3==2.0.2
> wrapt==1.15.0

**Comment by carlio** [comment]
Does this happen if you install an older version of prospector too? Or only the most recent 1.10 release?

**Comment by DaniBodor** [comment]
I just tested with 1.9.0 and get the same issue

**Comment by carlio** [comment]
Can you try it without conda? Often things like this are conda-related.

**Comment by DaniBodor** [comment]
How do I do this without conda? If I start my Ubuntu terminal, it automatically puts me in the conda base environment.

**Comment by carlio** [comment]
Using regular python and virtualenv? 

I'm afraid I have no idea what your setup is so I cannot help you there, you'll have to ask whoever set it up for help perhaps. I don't have enough information yet except that it does not work for your environment so I don't know what to say right now.

If you can try installing in different ways then it would lead to information that would help me.

**Comment by DaniBodor** [comment]
Solved. Will just quickly post solution in case someone else runs into same issue:

Apparently I had also prosector installed outside of any environment, which i discovered because `which prospector` showed me some path that clearly wasn't an environment (i.e. not something similar to "/home/<user>/miniconda3/bin/prospector").

Solution is:
run `conda deactivate` repeatedly, until I was not in any environment anymore (not even base).
run `pip uninstall prospector`
go back to environment where I was actually trying to use it and now it works.
