### ISSUE TITLE
prospector.yaml supports pylint's additional-builtins, but does not supportpyflakes/frosted.

### ISSUE THREAD

**Issue by jquast** [PyCQA/prospector#72]
I can tell pylint to ignore a list of builtins, such as for saltstack modules:

```
pylint:
    # static analysis and then some
    run: true
    options:
        additional-builtins:
            # from https://github.com/saltstack/salt/blob/develop/.pylintrc
            # NOTE: duplicated as PYFLAKES_BUILTINS for pyflakes in tox.ini
            - __salt__
            - __opts__
            (...)
```

For pyflakes/frosted, it is necessary to export an environment variable (`PYFLAKES_BUILTINS`) prior to executing prospector.  We should provide the same-named option as pylint to these other two tools and propagate their environment variables. An example setenv from tox.ini:

```
PYFLAKES_BUILTINS={env:PYFLAKES_BUILTINS:__salt__,__opts__,...}
```

**Comment by phw** [comment]
What happened here? This was closed, but no description given how it was fixed. I tried:

```
pyflakes:
  run: true
  additional-builtins:
    - _
   - N_
   - ngettext
```

But this is not accepted. Also tried with `builtins` instead of `additional-builtins`.
